### ISSUE TITLE
Another question about attribute syntaxt.

### ISSUE THREAD

**Issue by plamenGo** [imulab/go-scim#64]
Hi there, sorry if I am spamming you. Seeing the following 2 test failures in https://github.com/AzureAD/SCIMReferenceCode/wiki/Test-Your-SCIM-Endpoint

The below 2 URIs 

```
http://localhost:5001//Users?attributes=emails%5Btype+eq+%22work%22%5D
http://localhost:5001//Users?attributes=emails%5Bvalue+eq+%22emailName357%22%5D
```

result in 

```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "status": 400,
    "scimType": "invalidPath",
    "detail": "invalidPath: error compiling path"
}
```

It is not clear to me whether these are valid requests. Replacing the + chars with spaces also breaks the same way.

http://localhost:5001/Users?attributes=emails.type eq "work"
http://localhost:5001/Users?attributes=emails[value eq "emailName357"]

however these work fine:

Are these valid use cases or are these bad tests. Also, is it likely for these to be used at all, if my SCIM endpoint is only to receive data from Azure AD? The only reason I could think of these complex queries to be required is if they are somehow used for syncing the state between the SCIM  api and Azure AD.

**Comment by plamenGo** [comment]
Just wanted to mention, I am finding a few wrong tests in the Microsoft Postman collection I've been referencing, and I'm opening issues on their repo for those. Just want to bridge the difference, improve both projects, and end up with an implementation that I know will work well. Cheers!

**Comment by imulab** [comment]
@plamenGo No problem at all!

When specifying `attributes` To project the resource (i.e. return part of the resource), SCIM expects pure paths. Or at least that’s how interpreted the spec.

`/Users?attributes=emails` Is fine, it will return all users with their `returned=always` Attributes and the `emails` Attributes.

`/Users?attributes=emails.value` Is fine as well. It will return all users with their `returned=always` Attributes and the `emails` Attributes, but the `emails` Attributes will only contain the `value` Sub -attribute.

Specifying query predicates for `attributes` Which expects a true SCIM path will not work.

<del>If one wants to filter emails for a specific value, use `/Users?filter= emails%5Btype+eq+%22work%22%5D`.</del>

If you look at the `json` Package inside the `pkg` Module, you can see I didn’t use sophiscated parsing logic for these paths, as I didn’t think they should include predicates.

**Comment by perljusback** [comment]
@imulab I've just started to look at SCIM and stumbled across this package, seems like a great effort.
I've tried the:
/Users?filter= emails%5Btype+eq+%22work%22%5D

but it returns: invalidFilter: invalid character '[' around position 0 (hint:invalid character in path)

I could see that there's an implementation in CompilePath to compile it but filter doesn't allow [ in stateInPath.

**Comment by plamenGo** [comment]
@perljusback out of curiosity, what are you using SCIM for? I am trying to integrate with Azure AD to start with and later with GSuite and Okta. I am only trying to provision users one way, into my system, so for me the complex searching with attribute queries etc may not come into play. At least that's what I think based on my understanding of the protocol. For this reason I may choose to ignore any issues with attributes and filters, at least initially.

**Comment by perljusback** [comment]
@plamenGo atm we're not using i.

We currently have a grpc service for our internal provisioning.
 
The use cases you mention is one of the cases we're looking into using scim for the other is for the public api part to separate the workload between API and System, now if the complex query is needed is a good question and the reason i tried it was cuz @imulab  mentioned it in his response.

I did some investigation yesterday and done some changes to the filter to handle the usecase, but I will have to do some more testing to see so that it doesn't change the old behaviour but I can push a PR if it's of any interest after i'm done.

**Comment by imulab** [comment]
@perljusback Will take a look when I return probably tomorrow or the day after. Could you open a bug report?

**Comment by imulab** [comment]
@perljusback @plamenGo 

I just realized that I might have misled you in my previous reply. Sorry about that 🤦 

To clarify:
- projection parameters like `attributes` and `excludedAttributes` can only use paths like `userName`, `meta.created` and etc. These paths shall not include any predicates. As you can see in the `options.go` of the `json` package in the core module, they are treated as plain strings and is not compiled at all (only potential URN prefix stripped before processing).
- the filter parameter should use predicates like `userName eq "foo"` or `emails.value ew "@dot.com"`. If your predicate include `[` and/or `]`, it would be wrong, because that would entail a subset of path targets, which are still paths. For example, `emails[value eq "foo@bar.com"]` points to the `emails` property whose `value` sub-property has the said value. To filter a user resource whose `emails.value` has value `foo@bar.com`, use `filter=emails.value eq "foo@bar.com"` (HTML escape it of course).
- Filtered paths like `emails[value eq "foo@bar.com"].display`, or `photos[primary eq true]`, are generally used in PATCH operations. They indicate the precise property targets whose value is to be updated, added, or deleted.

I apologize for the misleading replies earlier. Apparently, iPad is not as useful when it comes to recollecting code yourself wrote before. I will strike-out the wrong answers above.
